### ISSUE TITLE
CLI not consistent between project & ticket commands with -R -T and -P flags

### ISSUE THREAD

**Issue by deadprogram** [hybridgroup/taskmapper#1]
Why is it that this works:
    $ tm project -R 666
    account : joe shmo
    allow_attachments : true
    ...

but this does not:
    $ tm ticket -R 2968599
    /Library/Ruby/Gems/1.8/gems/activeresource-2.3.8/lib/active_resource/connection.rb:194:in `handle_response': Failed with 404 Not Found (ActiveResource::ResourceNotFound)

Likewise, this works:
    $ tm ticket -T 2968599 -R
    accepted_at : Fri Apr 02 21:32:31 UTC 2010
    created_at : Mon Mar 29 15:47:21 UTC 2010

but this does not:
    $ tm project -P 2196 -R
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1448:in `complete': invalid option: -P (OptionParser::InvalidOption)

_[edited by kiafaldorius, formatting]_

**Comment by kiafaldorius** [comment]
Sorry, it was an oversight in the implementation. This has been fixed; both cases should now work as of 0.3.10. Thanks for the suggestion.
