### ISSUE TITLE
Cannot get any actions to work with pivotal

### ISSUE THREAD

**Issue by IdahoEv** [hybridgroup/taskmapper#18]
I can't get any requests to work with pivotal.  All attempts to call a method on a pivotal connection reply with 406: Not acceptable.

I've tried authenticating each of the following ways:
1) pivotal = TicketMaster.new(:pivotal)   # while ticketmaster.yml contains username and password  
2) pivotal = TicketMaster.new(:pivotal)  # while ticketmaster.yml contains pivotal token
3) pivotal = TicketMaster.new(:pivotal)  # while ticketmaster.yml contains username and token
4) pivotal = TicketMaster.new(:pivotal)  # while ticketmaster.yml contains username, password, and token
5) pivotal = TicketMaster.new(:pivotal, {:username => 'my username', :password => 'my password'})
6) pivotal = TicketMaster.new(:pivotal, {:username => 'my username', :password => 'my password', :token => 'my token'})
7) pivotal = TicketMaster.new(:pivotal, {:token => 'my token'})
8-10) repeat steps 5-7 without any ticketmaster.yml at all

In each of the above cases, pivotal contains a TM object connected to pivotal tracker, but calling pivotal.project.find   (or any other method) returns "406 Not Acceptable".

This happens both when run in console, _or_ when the code is put in Rakefile and executed there.

**Comment by IdahoEv** [comment]
When I'm trying ticketmaster.yml, it typically looks like this:

lighthouse:
  authentication:
    account: lrdesign
    username:  (my email)
    password: (my password)
  project: (project id#)

pivotal:
  authentication:
    username: (my email)
    password: (my password)
    token: (pivotal token)
  project: (project id)

**Comment by cored** [comment]
Hi IdahoEv,

I'm check on this issue and report back to you, thanks for using
ticketmaster :-)

2011/10/14 IdahoEv <
reply@reply.github.com>

> I can't get any requests to work with pivotal.  All attempts to call a
> method on a pivotal connection reply with 406: Not acceptable.
> 
> I've tried authenticating each of the following ways:
> 1) pivotal = TicketMaster.new(:pivotal)   # while ticketmaster.yml contains
> username and password
> 2) pivotal = TicketMaster.new(:pivotal)  # while ticketmaster.yml contains
> pivotal token
> 3) pivotal = TicketMaster.new(:pivotal)  # while ticketmaster.yml contains
> username and token
> 4) pivotal = TicketMaster.new(:pivotal)  # while ticketmaster.yml contains
> username, password, and token
> 5) pivotal = TicketMaster.new(:pivotal, {:username => 'my username',
> :password => 'my password'})
> 6) pivotal = TicketMaster.new(:pivotal, {:username => 'my username',
> :password => 'my password', :token => 'my token'})
> 7) pivotal = TicketMaster.new(:pivotal, {:token => 'my token'})
> 8-10) repeat steps 5-7 without any ticketmaster.yml at all
> 
> In each of the above cases, pivotal contains a TM object connected to
> pivotal tracker, but calling pivotal.project.find   (or any other method)
> returns "406 Not Acceptable".
> 
> This happens both when run in console, _or_ when the code is put in
> Rakefile and executed there.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hybridgroup/ticketmaster/issues/18

## 

Rafael George

**Comment by cored** [comment]
I fixed this problem please test again
