### ISSUE TITLE
Dummy project's tickets returns Stack level too deep on 1.9.2

### ISSUE THREAD

**Issue by ldenman** [hybridgroup/taskmapper#4]
Hey ya! I'm not sure if you guys are shooting for 1.9.2 support quite yet, but thought I'd bring this to your attention.

In IRB on 1.9.2:

```
>> require 'ticketmaster'
>> d = TicketMaster::Provider::Dummy.new
>> d.projects.first.tickets
#=> SystemStackError: stack level too deep
    from /home/lake/.rvm/gems/ruby-1.9.2-p0/gems/hashie-0.4.0/lib/hashie/mash.rb:161
```

I haven't really dug into this issue -- seems to actually lie in Hashie, anyhow. Just keeping you guys informed.

Thanks for your sweet project. Peace!

**Comment by kiafaldorius** [comment]
We know there are problems on 1.9.2. We'd like to support it...and will in due time. I may phase out Hashie for a more custom attributes implementation during ticketmaster v2. I just don't have that much time at the moment...

Thanks for trying ticketmaster!
