### ISSUE TITLE
Provider request: taskmapper-trello

### ISSUE THREAD

**Issue by rpavlik** [hybridgroup/taskmapper#47]
Trello is like Kanbanpad but simultaneously simpler and more powerful.

There's already an abundance of wrappers and gems for Trello's API. See https://trello.com/docs/  (and the horde version/version you can add to https://trello.com/card/known-wrappers-projects-using-the-trello-api/4ed7e27fe6abb2517a21383d/40 )

**Comment by cored** [comment]
We probably add this new provider, stay tune :-)

**Comment by stewart** [comment]
A [taskmapper-trello](https://github.com/hybridgroup/taskmapper-trello) provider has been written and pushed to RubyGems. Please let us know what you think, and if there are any missing features!
