### ISSUE TITLE
taskmapper-cli dependency not met

### ISSUE THREAD

**Issue by gaurav-notnetspi** [hybridgroup/taskmapper#50]
taskmapper-cli dependency is not met during installation of taskmapper because taskmapper-cli gem has been renamed to tm. The taskmapper Gemfile should reflect that change. 

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: taskmapper requires taskmapper-cli (= 0.0.1)

**Comment by cored** [comment]
Will research the issue, thanks.

**Comment by cored** [comment]
@gaurav-netspi The issue happens because of the providers dependency pointing to taskmapper 0.8.0, but there's no relationship between tm and taskmapper-cli the later is the name of the actual gem that contains the code for the CLI and tm is the command. As there are a lot of providers it will take me some hours to fix this, but I will solve it and release a patched version soon.

**Comment by gaurav-notnetspi** [comment]
Thanks @cored. Appreciate you looking into this.

**Comment by cored** [comment]
@gaurav-netspi Latest version of Taskmapper solve this problem, it was a dependency issue between older versions of taskmapper and this one. I had to isolate the CLI for the moment but it will be integrate it back as soon as I solve another structural issue inside the CLI; for now you can use the library with version 1.0.1. Hope this helps you; if you need anything else just let me know I would like the feedback. 

Thanks again.

**Comment by gaurav-notnetspi** [comment]
Thanks @cored. The issue is resolved now. Look forward to trying it out.

**Comment by cored** [comment]
Great to heard that. If you need anything else just let me know.

On 17 April 2013 11:57, gaurav-netspi notifications@github.com wrote:

> Thanks @cored https://github.com/cored. The issue is resolved now. Look
> forward to trying it out.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hybridgroup/taskmapper/issues/50#issuecomment-16514584
> .

## 

Rafael George
