### ISSUE TITLE
Borked Dependencies?

### ISSUE THREAD

**Issue by freeformz** [hybridgroup/taskmapper#6]
$ gem list

**\* LOCAL GEMS ***

rake (0.8.7)
rdoc (2.5.11)

$ gem install ticketmaster-lighthouse
ERROR:  Error installing ticketmaster-lighthouse:
    activeresource requires activesupport (= 3.0.1, runtime)

$ gem install activeresource
Successfully installed activesupport-3.0.1
Successfully installed builder-2.1.2
Successfully installed i18n-0.4.1
Successfully installed activemodel-3.0.1
Successfully installed activeresource-3.0.1
5 gems installed
Installing ri documentation for activesupport-3.0.1...
Installing ri documentation for builder-2.1.2...
Installing ri documentation for i18n-0.4.1...
Installing ri documentation for activemodel-3.0.1...
Installing ri documentation for activeresource-3.0.1...
Installing RDoc documentation for activesupport-3.0.1...
Installing RDoc documentation for builder-2.1.2...
Installing RDoc documentation for i18n-0.4.1...
Installing RDoc documentation for activemodel-3.0.1...
Installing RDoc documentation for activeresource-3.0.1...

$ gem install ticketmaster-lighthouse
ERROR:  Error installing ticketmaster-lighthouse:
    activeresource requires activesupport (= 2.3.10, runtime)

**Comment by kiafaldorius** [comment]
Thanks for the patch! =]

Released as version 0.4.0
