### ISSUE TITLE
Redmine Support?

### ISSUE THREAD

**Issue by notch8-old** [hybridgroup/taskmapper#8]
During the RubyConf X lightning talk I believe you mentioned that someone is working on Redmine support, but I do not see it here on Github.  If someone is working on it, I'd like to help, otherwise I'd be happy to start working on it.
Thanks,
Rob Kaufman

**Comment by deadprogram** [comment]
HI, Rob

Despite severa comments, looks like no one has actually gotten started on this:
https://github.com/search?q=ticketmaster-redmine&type=Everything&repo=&langOverride=&start_value=1

So PLEASE feel free to work on it, and let us know how we can assist, or alternately when we can add a link to your repo/gem to the list of providers.

Regards,
Ron
