### ISSUE TITLE
ticketmaster CLI assumes that project ids are numeric

### ISSUE THREAD

**Issue by cowboyd** [hybridgroup/taskmapper#9]
This is problematic for the Jira implementation

The jira convention is to use 3 letter strings as project ids.

However, when interacting from the command line, tm always converts the project id to an integer.  If the key is not a parseable integer, then it should be passed in as-is, and not converted to 0.

**Comment by kiafaldorius** [comment]
I have removed the integer conversion entirely. A quick test of the providers seems like they're generally ok with it.

This has been pushed and released as 0.5.2

Thanks!

**Comment by cowboyd** [comment]
whoa! thanks for the quick turnaround.

**Comment by kiafaldorius** [comment]
You're welcome! Thanks for working on the Jira provider. Please let us know when it finishes so we can add it to the list =]
